apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80

  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause:
            duration: 30s

        - setWeight: 50
        - pause:
            duration: 30s

        - setWeight: 100